# Generated by Django 3.0.3 on 2020-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(max_length=264, null=True, unique=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('First_Name', models.CharField(max_length=200, null=True)),
                ('Last_Name', models.CharField(max_length=200, null=True)),
                ('USN', models.CharField(max_length=200, null=True)),
                ('Gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=15, null=True)),
                ('Tenth_Board', models.IntegerField(choices=[('1', 'STATE'), ('2', 'CBSE'), ('3', 'ICSE')], null=True)),
                ('Tenth_Medium', models.IntegerField(choices=[('1', 'English'), ('2', 'Kannada')], null=True)),
                ('Tenth_Math', models.IntegerField(null=True)),
                ('Tenth_Science', models.IntegerField(null=True)),
                ('Tenth_Eng', models.IntegerField(null=True)),
                ('Tenth_Total', models.IntegerField(null=True)),
                ('Twelth_Math', models.IntegerField(null=True)),
                ('Twelth_Physics', models.IntegerField(null=True)),
                ('Twelth_Chemistry', models.IntegerField(null=True)),
                ('Twelth_Optional', models.IntegerField(null=True)),
                ('Twelth_Eng', models.IntegerField(null=True)),
                ('Twelth_Total', models.IntegerField(null=True)),
                ('Twelth_Board', models.IntegerField(choices=[('1', 'STATE'), ('2', 'CBSE'), ('3', 'ICSE')], null=True)),
                ('English_Profieciency', models.IntegerField(choices=[('1', 'BEGINNER'), ('2', 'INTERMEDIATE'), ('3', 'NATIVE SPEAKER')], null=True)),
                ('CETorComedk', models.IntegerField(null=True)),
                ('Extra_curricular_participation', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Extra_curricular_activity', models.CharField(max_length=200, null=True)),
                ('Levelof_achievement', models.IntegerField(choices=[('1', 'SCHOOL LEVEL'), ('2', 'COLLEGE LEVEL'), ('3', 'NATIONAL LEVEL'), ('4', 'INTERNATIONAL LEVEL')], null=True)),
                ('FatherQualification', models.IntegerField(choices=[('1', 'BELOW TENTH'), ('2', 'TENTH'), ('3', 'BACHELORS'), ('4', 'MASTERS'), ('5', 'PHD')], null=True)),
                ('MotherQualification', models.IntegerField(choices=[('1', 'BELOW TENTH'), ('2', 'TENTH'), ('3', 'BACHELORS'), ('4', 'MASTERS'), ('5', 'PHD')], null=True)),
                ('FamilyIncome', models.IntegerField(choices=[('1', 'BELOW 1 LAKH'), ('2', '1L-2L'), ('3', '2L-4L'), ('4', '4L-6L'), ('5', 'Above 6 lakh')], null=True)),
                ('Are_you_a_migrate', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Distance', models.IntegerField(null=True)),
                ('Branch', models.CharField(max_length=200, null=True)),
                ('First_Sem', models.FloatField(null=True)),
                ('Second_Sem', models.FloatField(null=True)),
                ('Third_Sem', models.FloatField(null=True)),
                ('Fourth_Sem', models.FloatField(null=True)),
                ('Fifth_Sem', models.FloatField(null=True)),
                ('Sixth_Sem', models.FloatField(null=True)),
                ('Seventh_Sem', models.FloatField(null=True)),
                ('Eight_Sem', models.FloatField(null=True)),
                ('CGPA', models.FloatField(null=True)),
                ('Extra_activity', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Specify_extraactivity', models.CharField(max_length=500, null=True)),
                ('What_level_of_participation', models.IntegerField(choices=[('1', 'SCHOOL LEVEL'), ('2', 'COLLEGE LEVEL'), ('3', 'NATIONAL LEVEL'), ('4', 'INTERNATIONAL LEVEL')], null=True)),
                ('Can_you_handle_a_professional_team', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Are_you_a_team_player', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Have_you_worked_in_the_same_field', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('How_do_describe_yourself_as', models.IntegerField(choices=[('1', 'Introvert'), ('1.5', 'Extrovert'), ('2', 'Ambivert')], null=True)),
                ('Do_you_take_initiative_in_a_work', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Are_you_a_procrastinator', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Logical_reasoning', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True)),
                ('Have_you_been_in_any_research', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Internship', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Company_demand', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Relationships', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Personnel_choice', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Campus_recruid', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Higher_education', models.FloatField(choices=[('1', 'NO'), ('1.5', 'Maybe'), ('2', 'YES')], null=True)),
                ('Package', models.FloatField(null=True)),
                ('joinyear', models.IntegerField(null=True)),
            ],
        ),
    ]
