# Generated by Django 3.0.3 on 2020-06-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universityapp', '0002_auto_20200619_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True),
        ),
    ]
