# Generated by Django 3.0.3 on 2020-07-15 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Date',
            field=models.DateTimeField(default=datetime.date.today, editable=False),
        ),
    ]
