# Generated by Django 3.0.3 on 2020-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Organization',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
