# Generated by Django 3.0.7 on 2020-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Gender', models.IntegerField(choices=[('1', 'Male'), ('2', 'Female')], max_length=15, null=True)),
                ('Tenth_Board', models.IntegerField(choices=[('1', 'STATE'), ('2', 'CBSE'), ('3', 'ICSE')], max_length=2, null=True)),
                ('Tenth_Medium', models.IntegerField(choices=[('1', 'English'), ('2', 'Kannada')], max_length=15, null=True)),
            ],
        ),
    ]
