# Generated by Django 2.2.13 on 2020-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='student',
            name='Annual_family_income',
            field=models.CharField(choices=[('1', 'BELOW 1 LAKH'), ('2', '1L-2L'), ('3', '2L-4L'), ('4', '4L-6L'), ('5', 'Above 6 lakh')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Are_you_a_procrastinator',
            field=models.CharField(choices=[('1', 'NO'), ('2', 'YES')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Are_you_open_to_a_relationships',
            field=models.CharField(choices=[('1', 'NO'), ('2', 'YES')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CET_or_Comedk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Did_you_migrate_frome_hometown',
            field=models.CharField(choices=[('1', 'NO'), ('2', 'YES')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Distance_between_school_or_college_and_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Do_you_take_initiative_in_a_work',
            field=models.CharField(choices=[('1', 'NO'), ('2', 'YES')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='English_Profieciency',
            field=models.CharField(choices=[('1', 'BEGINNER'), ('2', 'INTERMEDIATE'), ('3', 'NATIVE SPEAKER')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Extra_curricular_activity',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Extra_curricular_participation',
            field=models.CharField(choices=[('1', 'NO'), ('2', 'YES')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='FatherQualification',
            field=models.CharField(choices=[('1', 'BELOW TENTH'), ('2', 'TENTH'), ('3', 'BACHELORS'), ('4', 'MASTERS'), ('5', 'PHD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='How_do_describe_yourself_as',
            field=models.CharField(choices=[('1', 'Introvert'), ('1.5', 'Extrovert'), ('2', 'Ambivert')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Interested_in_research',
            field=models.CharField(choices=[('1', 'NO'), ('2', 'YES')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Levelof_achievement',
            field=models.CharField(choices=[('1', 'SCHOOL LEVEL'), ('2', 'COLLEGE LEVEL'), ('3', 'NATIONAL LEVEL'), ('4', 'INTERNATIONAL LEVEL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Logical_reasoning',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MotherQualification',
            field=models.CharField(choices=[('1', 'BELOW TENTH'), ('2', 'TENTH'), ('3', 'BACHELORS'), ('4', 'MASTERS'), ('5', 'PHD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Tenth_Eng',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Tenth_Math',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Tenth_Science',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Tenth_Total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Twelth_Board',
            field=models.CharField(choices=[('1', 'STATE'), ('2', 'CBSE'), ('3', 'ICSE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Twelth_Chemistry',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Twelth_Eng',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Twelth_Math',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Twelth_Optional',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Twelth_Physics',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Twelth_Total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Was_joining_engineering_your_personnel_choice',
            field=models.CharField(choices=[('1', 'NO'), ('2', 'YES')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Tenth_Board',
            field=models.CharField(choices=[('1', 'STATE'), ('2', 'CBSE'), ('3', 'ICSE')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Tenth_Medium',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Kannada')], max_length=15, null=True),
        ),
    ]
