# Generated by Django 3.0.3 on 2020-07-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20200629_2311'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='basicapp_student',
        ),
    ]
