# Generated by Django 3.0.3 on 2020-07-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20200713_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pred_cocur',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_eight_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_first_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_five_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_four_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_intern',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_pack',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_secd_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_seven_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_six_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_third_sem',
        ),
    ]
