# Generated by Django 3.0.3 on 2020-07-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_auto_20200713_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pred_III_sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_II_sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_IV_sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_I_sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_VIII_sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_VII_sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_VI_sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_V_sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_cocur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_intern',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pred_pack',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
