# Generated by Django 3.0.3 on 2020-07-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_auto_20200713_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pred_III_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_II_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_IV_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_I_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_VIII_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_VII_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_VI_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_V_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_avg_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_cocur',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_intern',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pred_pack',
        ),
    ]
