# Generated by Django 3.0.3 on 2020-07-13 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0010_auto_20200713_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
