# Generated by Django 3.0.3 on 2020-07-13 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0012_auto_20200714_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
