# Generated by Django 3.0.3 on 2020-08-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0015_student_merit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='merit',
        ),
    ]
